[build]
  command = "apt-get update && apt-get install -y tesseract-ocr && pip install -r requirements.txt"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.10"

[[plugins]]
  package = "netlify-plugin-python-runtime"

[dev]
  command = "python app.py"
  port = 5000
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
