services:
  - type: web
    name: time-tracker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: RENDER
        value: true
    healthCheckPath: /
    numInstances: 1
